version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: agenda-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: agenda_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
